# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('target_pos_x', models.FloatField(null=True)),
                ('target_pos_y', models.FloatField(null=True)),
                ('target_pos_z', models.FloatField(null=True)),
                ('camera_pos_x', models.FloatField(null=True)),
                ('camera_pos_y', models.FloatField(null=True)),
                ('camera_pos_z', models.FloatField(null=True)),
                ('annotation_text', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('path', models.ImageField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\opm\\opm\\tours/static/renders')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('description', models.TextField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('object_path', models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\opm\\opm\\tours/static/renders')),
                ('colormap_path', models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\opm\\opm\\tours/static/renders')),
                ('specmap_path', models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\opm\\opm\\tours/static/renders')),
                ('normalmap_path', models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\opm\\opm\\tours/static/renders')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('render', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Render')),
            ],
        ),
        migrations.AddField(
            model_name='paragraph',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='image',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
    ]
