# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='/var/data/opm/')),
            ],
        ),
    ]
