# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_render'),
    ]

    operations = [
        migrations.RenameField(
            model_name='render',
            old_name='path',
            new_name='object_path',
        ),
        migrations.AddField(
            model_name='render',
            name='colormap_path',
            field=models.FileField(default=django.utils.timezone.now, upload_to='/var/data/opm/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='render',
            name='normalmap_path',
            field=models.FileField(default=django.utils.timezone.now, upload_to='/var/data/opm/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='render',
            name='specmap_path',
            field=models.FileField(default=django.utils.timezone.now, upload_to='/var/data/opm/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='render',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
