# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20170711_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\redpath_prod\\opm\\tours/media/renders'),
        ),
        migrations.AlterField(
            model_name='render',
            name='colormap_path',
            field=models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\redpath_prod\\opm\\tours/media/renders'),
        ),
        migrations.AlterField(
            model_name='render',
            name='normalmap_path',
            field=models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\redpath_prod\\opm\\tours/media/renders'),
        ),
        migrations.AlterField(
            model_name='render',
            name='object_path',
            field=models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\redpath_prod\\opm\\tours/media/renders'),
        ),
        migrations.AlterField(
            model_name='render',
            name='specmap_path',
            field=models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\redpath_prod\\opm\\tours/media/renders'),
        ),
    ]
