# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20170114_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='render',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Render'),
        ),
    ]
