# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_render'),
    ]

    operations = [
        migrations.AlterField(
            model_name='render',
            name='colormap_path',
            field=models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\opm\\opm\\tours/static/renders'),
        ),
        migrations.AlterField(
            model_name='render',
            name='normalmap_path',
            field=models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\opm\\opm\\tours/static/renders'),
        ),
        migrations.AlterField(
            model_name='render',
            name='object_path',
            field=models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\opm\\opm\\tours/static/renders'),
        ),
        migrations.AlterField(
            model_name='render',
            name='specmap_path',
            field=models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\opm\\opm\\tours/static/renders'),
        ),
    ]
