# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_render'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='render',
            name='colormap_path',
            field=models.FileField(upload_to='/home/fxleblanc/Repositories/opm/tours/static/renders'),
        ),
        migrations.AlterField(
            model_name='render',
            name='normalmap_path',
            field=models.FileField(upload_to='/home/fxleblanc/Repositories/opm/tours/static/renders'),
        ),
        migrations.AlterField(
            model_name='render',
            name='object_path',
            field=models.FileField(upload_to='/home/fxleblanc/Repositories/opm/tours/static/renders'),
        ),
        migrations.AlterField(
            model_name='render',
            name='specmap_path',
            field=models.FileField(upload_to='/home/fxleblanc/Repositories/opm/tours/static/renders'),
        ),
    ]
