# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20170711_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tours', models.ManyToManyField(to='tours.Tour')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
