# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20170128_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
