# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20170128_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('path', models.ImageField(upload_to='/home/fxleblanc/Repositories/opm/tours/static/renders')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
