# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tourgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('path', models.FileField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\redpath_prod\\opm\\tours/media//videos')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
