# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(help_text='Write down the position of the content as an integer. Increasing positions are placed on a top to bottom scale.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tour',
            field=models.ForeignKey(help_text='Select to which Tour you want to link this content', null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='position',
            field=models.IntegerField(help_text='Write down the position of the content as an integer. Increasing positions are placed on a top to bottom scale.'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='tour',
            field=models.ForeignKey(help_text='Select to which Tour you want to link this content', null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(help_text='Only mp4 format is suported', upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\redpath_prod\\opm\\tours/media//videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='position',
            field=models.IntegerField(help_text='Write down the position of the content as an integer. Increasing positions are placed on a top to bottom scale.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tour',
            field=models.ForeignKey(help_text='Select to which Tour you want to link this content', null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
    ]
