# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\redpath_prod\\opm\\tours/media//images')),
                ('current_status', models.CharField(help_text='Example: PhD (c) Scientology', max_length=500)),
                ('position', models.CharField(help_text='Example: VP Communications', max_length=200)),
            ],
        ),
    ]
