# -*- coding: utf-8 -*-

# Generated by Django 1.10.5 on 2018-01-06 00:12

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='C:\\Users\\Tfmenard\\Documents\\GitHub\\redpath_prod\\opm\\media//images')),
                ('professional_background', models.CharField(help_text='Example: PhD (c) Scientology', max_length=500)),
                ('project_position', models.CharField(help_text='Example: VP Communications', max_length=200)),
            ],
        ),
    ]
