# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='current_status',
            new_name='professional_background',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='position',
            new_name='project_position',
        ),
    ]
